### ISSUE TITLE
Tasks list for release

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#138]
Highest priority:
- [x] Tox integration for local CI check
- [x] Travis CI
- [x] Documentation setup (readthedocs.org)
- [x] Coverage metric integration (codecov.io)
- [x] Code quality checks like pylint/flake metrics
- [x] License and other formalities
- [x] Logging
- [x] Clean up non-essential code
- [x] remove matlab mst from run time options. preserve code for testing purposes
- [x] Uniform run_pyrate workflow for single process/mpi operation (https://github.com/GeoscienceAustralia/PyRate/issues/139)
- [x] Review (and close) outstanding Git Issues
- [ ] Performance testing
- [x] Move temp files in a temp dir

Secondary priority:
- [x] Python3 support 
- [x] Anaconda based env
- [x] Use joblib for python multiprocess setup
- [x] Use mpi4py instead of pypar
- [x] TASK #1 Enable use of Orbital error network method (method 2) - see #147
- [ ] TASK #3 Coherence map import and utilisation for masking ifgs
- [ ] Use coherence as weights in MST calculations
- [x] Pypi integration
- [x] TASK #2 Implement spatio-temporal filter method for atmosphere mitigation
- [ ] Windows compatibility and CI (appveyor)
- [ ] Update the viewer program
- [ ] Weather model correction code (PyAPS) integration on linux
- [ ] Implement elevation-phase method for mitigating stratified atmosphere
- [ ] Use yaml based config file
- [ ] PyUp integration (pyup.io)
- [x] MPI test for different orbital correction polynomial model options

**Comment by basaks** [comment]
TASK 1 done with caveat:  #147.
Pypi integration ready to be pushed into pypi. Need GA gihub superuser access. Will raise an issue with instructions on how to perform this.

**Comment by mcgarth** [comment]
Closing with release of version 0.2.0 d0a634b. Unticked items subject to future implementation. First priority: Coherence map import and utilisation for masking noisy pixels in ifgs
